name: 'solutions-hubspk-ne-rg'

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - solutions/CoreInfra/HubAndSpoke*

variables:
  - template: pipeline.variables.yml

stages:
# ---------------- #
# Validation Stage #
# ---------------- #
  - stage:
    displayName: WhatIf
    jobs:
    #Resource Groups
    #---------------
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/parameters.json'
          whatif: true
          checkoutRepositories:
            - self

    #Network Security Groups
    #-----------------------
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: hubNetworkSecurityGroups
          displayName: 'Hub Network Security Groups'
          modulePath: '/modules/Microsoft.Network/networkSecurityGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/networkSecurityGroups/hub-parameters.json'
          whatif: true
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: spokeNetworkSecurityGroups
          displayName: 'Network Security Groups'
          modulePath: '/modules/Microsoft.Network/networkSecurityGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/networkSecurityGroups/spoke-parameters.json'
          whatif: true
          checkoutRepositories:
            - self

    #RouteTables
    #-----------
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: routeTables
          displayName: 'Route Tables'
          modulePath: '/modules/Microsoft.Network/routeTables/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/routeTables/parameters.json'
          whatif: true
          checkoutRepositories:
            - self

    # VirtualNetwork
    # --------------
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: hubVirtualNetwork
          displayName: 'Hub Virtual Network'
          modulePath: '/modules/Microsoft.Network/virtualNetworks/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/virtualNetworks/hub-parameters.json'
          whatif: true
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: spokeVirtualNetwork
          displayName: 'Spoke Virtual Network'
          modulePath: '/modules/Microsoft.Network/virtualNetworks/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/virtualNetworks/spoke-parameters.json'
          whatif: true
          checkoutRepositories:
            - self

# ---------------- #
# Deployment Stage #
# ---------------- #
  - stage:
    displayName: Deploy
    jobs:
    #Resource Groups
    #---------------
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/parameters.json'
          checkoutRepositories:
            - self

    #Network Security Groups
    #-----------------------
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: hubnetworkSecurityGroups
          displayName: 'Hub Network Security Groups'
          modulePath: '/modules/Microsoft.Network/networkSecurityGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/networkSecurityGroups/hub-parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: spokeNetworkSecurityGroups
          displayName: 'Spoke Network Security Groups'
          modulePath: '/modules/Microsoft.Network/networkSecurityGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/networkSecurityGroups/spoke-parameters.json'
          checkoutRepositories:
            - self

    #RouteTables
    #-----------
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: routeTables
          displayName: 'Route Tables'
          modulePath: '/modules/Microsoft.Network/routeTables/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/routeTables/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: nvaRouteTables
          displayName: 'NVA Route Tables'
          modulePath: '/modules/Microsoft.Network/routeTables/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/routeTables/nva-parameters.json'
          checkoutRepositories:
            - self

    # VirtualNetworks
    # ---------------
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: hubVirtualNetworks
          displayName: 'Hub Virtual Networks'
          modulePath: '/modules/Microsoft.Network/virtualNetworks/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/virtualNetworks/hub-parameters.json'
          checkoutRepositories:
            - self
          dependsOn:
            - hubnetworkSecurityGroups
            - routeTables
            - nvaRouteTables

      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: spokeVirtualNetwork
          displayName: 'Spoke Virtual Network'
          modulePath: '/modules/Microsoft.Network/virtualNetworks/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/HubAndSpoke/PipelineOrchestrated/virtualNetworks/spoke-parameters.json'
          checkoutRepositories:
            - self
          dependsOn:
            - spokeNetworkSecurityGroups
            - routeTables
