name: 'solutions-ne-spoke-rg'

parameters:
- name: whatif
  displayName: Validate template file via connection
  type: boolean
  default: true

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - solutions/CoreInfra/Spoke*

variables:
  - template: pipeline.variables.yml

stages:
  - stage:
    displayName: WhatIf
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: networkSecurityGroups
          displayName: 'Network Security Groups'
          modulePath: '/modules/Microsoft.Network/networkSecurityGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/networkSecurityGroups/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: routeTables
          displayName: 'Route Tables'
          modulePath: '/modules/Microsoft.Network/routeTables/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/routeTables/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: virtualNetworks
          displayName: 'Virtual Networks'
          modulePath: '/modules/Microsoft.Network/virtualNetworks/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/virtualNetworks/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: keyVault
          displayName: 'Key Vault'
          modulePath: '/modules/Microsoft.KeyVault/vaults/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/keyVaults/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: storageAccount
          displayName: 'Storage Account'
          modulePath: '/modules/Microsoft.Storage/storageAccounts/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/storageAccounts/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: logAnalytics
          displayName: 'Log Analytics'
          modulePath: '/modules/Microsoft.OperationalInsights/workspaces/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/logAnalytics/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: userAssignedIdentities
          displayName: 'User Assigned Identities'
          modulePath: '/modules/Microsoft.ManagedIdentity/userAssignedIdentities/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/userAssignedIdentities/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: recoveryServices
          displayName: 'Recovery Services'
          modulePath: '/modules/Microsoft.RecoveryServices/vaults/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/recoveryServices/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self

  - stage:
    displayName: Deploy
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: networkSecurityGroups
          displayName: 'Network Security Groups'
          modulePath: '/modules/Microsoft.Network/networkSecurityGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/networkSecurityGroups/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: routeTables
          displayName: 'Route Tables'
          modulePath: '/modules/Microsoft.Network/routeTables/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/routeTables/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: virtualNetworks
          displayName: 'Virtual Networks'
          modulePath: '/modules/Microsoft.Network/virtualNetworks/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/virtualNetworks/parameters.json'
          checkoutRepositories:
            - self
          dependsOn:
            - networkSecurityGroups
            - routeTables
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: keyVault
          displayName: 'Key Vault'
          modulePath: '/modules/Microsoft.KeyVault/vaults/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/keyVaults/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: storageAccount
          displayName: 'Storage Account'
          modulePath: '/modules/Microsoft.Storage/storageAccounts/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/storageAccounts/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: logAnalytics
          displayName: 'Log Analytics'
          modulePath: '/modules/Microsoft.OperationalInsights/workspaces/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/logAnalytics/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: userAssignedIdentities
          displayName: 'User Assigned Identities'
          modulePath: '/modules/Microsoft.ManagedIdentity/userAssignedIdentities/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/userAssignedIdentities/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: recoveryServices
          displayName: 'Recovery Services'
          modulePath: '/modules/Microsoft.RecoveryServices/vaults/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/recoveryServices/parameters.json'
          checkoutRepositories:
            - self
